services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - app-net
    environment:
      FLASK_ENV: development
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
      DB_HOST: db

  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-net

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

networks:
  app-net:

volumes:
  pgdata: